services:
  es:
    image: elasticsearch:7.6.2
    container_name: es762
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    restart: always
  micseres:
    build: .
    ports:
      - 8080:8080
    restart: always